### ISSUE TITLE
missing column 'teams.seed'

### ISSUE THREAD

**Issue by roelvs** [tamuctf/ctfd-instancing-plugin#2]
After installation of this plugin (in an empty ctfd setup), the database seems broken:

`
OperationalError: (sqlite3.OperationalError) no such column: teams.seed [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT teams.id AS teams_id, teams.name AS teams_name, teams.email AS teams_email, teams.password AS teams_password, teams.website AS teams_website, teams.affiliation AS teams_affiliation, teams.country AS teams_country, teams.bracket AS teams_bracket, teams.banned AS teams_banned, teams.verified AS teams_verified, teams.admin AS teams_admin, teams.joined AS teams_joined, teams.seed AS teams_seed \nFROM teams \nWHERE teams.banned = 0) AS anon_1']
`

running against : https://github.com/tamuctf/CTFd (current)

**Comment by ameserole** [comment]
We haven't bumped our CTFd fork in a long time and I don't think we actually used it in our competition. Maybe try running it against the current version https://github.com/CTFd/CTFd/tree/1.0.3 
I the mean time we will start looking at this.

**Comment by roelvs** [comment]
I applied the patch manually against CTFd 1.0.3 and the server boots fine, but if the 'instanced' challenge type is selected, the form is empty...

I'm not a Flask/CTFd expert, but if you have any suggestions on what to try, they would be much appreciated!

**Comment by ameserole** [comment]
Sorry it took me a while but I finally had the time to sit down and look at it.
Currently this plugin supports CTFd version 1.0.2. More accurate instructions would be:
1. `git clone` this repo into the CTFd/plugins directory
2. Move the `models.patch` file into the base directory or your CTFd repo
3. In the base repo run `git checkout 1.0.2` to checkout to the currently working ctfd version.
4. Run `git apply --check models.patch` to test the patch
5. Run `git apply models.patch` to add the instancing models and suppress flask migrations
6. Move the `template/user` and `template/admin` files into `CTFd/static/<theme>/js/templates/challenges/instanced` and `CTFd/static/admin/js/templates/challenges/instanced` respectively, where `<theme>` is your theme ('origonal' by default)

Make sure when copying the static files you copy the files into the `instanced` directory and not `instanced/user/files...` 

I have updated the README with the new instructions. 
Did this work?

**Comment by ameserole** [comment]
I haven't heard back in a while so I am going to close this issue.

**Comment by roelvs** [comment]
it works great, sorry I couldn't come back to you any sooner...
